print('========DESAFIO 04========')
n = input('\033[7;97mDigite algo:\033[m ')
print('\033[97m{} é do tipo {}'.format(n, type(n)))
print('n é número:', n.isnumeric())
print('n é alfabético:', n.isalpha())
print('n é maiúsculo:', n.isupper())
print('n é minúsculo:', n.islower())
print('n é título:', n.istitle())
print('n é alfanumérico:', n.isalnum())
print('n é espaço:', n.isspace())
print('n é imprimível:', n.isprintable())
print('n é isso aí:', n.isascii())
print('n é decimal:', n.isdecimal())
print('n é indentificador:', n.isidentifier())
print('n é dígito:', n.isdigit(), '\033[m')
